# rename this file to config.yaml before start

# qqbot account, not needed anymore for qrcode authentication
account:  2769546520
password: "123"

# server to view verification code, not required for mac
port: 3100
host: localhost

nickname: "小萌姬"

# message handling, ignore offline message 20 min ago
# offline_msg_keeptime: 1200

# plugin list
plugins:
    - help
    - debug
    - apiserver
    - tuling

# apiserver plugin configration
api_port:  3200
api_token: ''


# tuling
api_key: "9f9a5957a0134f5d84ec44811525ee9e"
